package com.user.model;

public enum Certifications {
    AGILE, ORACLE, AWS, IRC,MICROSOFT,CLOUDCOMPUTING,
    GCP,IBM,PALO,SALESFORCE,PEGA,REDHAT,SCRUM,
    CITRIX,CHECKPOINT,DELLEMC,HPE,AZURE,ADOBE
}
