server:
  port: 8888
  # This provides the uri of the central repository used by all services
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fsdnas/ConnectionsConfigServer.git