server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

spring:
  application:
    name: JOB-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/connections
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

#  config:
#    import: configserver:http://localhost:8888/
#  profiles:
#    active: dev,prod


#Logging:
#  level:
#    root: WARN
#    org:
#      springframework: debug
#    com:
#      jobs: debug
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss} [%thread] -> %msg%n
#  filename: C:/Users/RajasekharMandireddy/Training/Group Project Connections/Connections/connections-jobs-service/log/app.log

#      #set default logging
#      logging.level.root=WARN
#
#      # setting the logging level
#      logging.level.org.springframework=debug
#      logging.level.com.greetapp=debug
#
#      # logging pattern for console
#      logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] -> %msg%n
#
#      #appending to a file
#      logging.file.name=C:/Users/RajasekharMandireddy/Training/IntelliJ/spring/spring-logging-restapi/log/app.log