server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

spring:
  application:
    name: PROFILE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/connections
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

#  config:
#    import: configserver:http://localhost:8888/
#  profiles:
#    active: dev,prod
